# docker-compose-monitoring.yml

version: '3'

services:
  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    ports:
      - "8086:8086"
    networks:
      - gachonoj-network
    environment:
      - INFLUXDB_HTTP_AUTH_ENABLED=false
      - INFLUXDB_DB=k6
    restart : on-failure


  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    networks:
      - gachonoj-network
    environment:
      - TZ=Asia/Seoul
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    restart : on-failure

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    user: "$UID:$GID"
    networks:
      - gachonoj-network
    ports:
      - "3000:3000"
    environment:  
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    volumes:
      - ./grafana-data:/var/lib/grafana  
      - ./grafana:/etc/grafana/provisioning/

    depends_on:
      - prometheus

    restart : on-failure
  
  k6:
    image: grafana/k6:latest
    container_name: k6
    networks:
      - gachonoj-network
    ports:
      - "6565:6565"
    environment:
      - K6_OUT=influxdb=http://influxdb:8086/k6
    volumes:
      - ./examples:/scripts

networks:
  gachonoj-network:
    external: true    
